### ISSUE TITLE
Update to Offsets & Whatnot for ACNH 2.0?

### ISSUE THREAD

**Issue by ThatAnarchyDude** [MyShiLingStar/ACNHPoker#10]
I'm not sure if this is the correct place to mention this, but ACNH 2.0 just dropped (a day early).
I just wanted to make sure you were aware of it because I LOOOOVE ACNH Poker & am dying to use once more...in 2.0.

Thank you for all of your hard work.
It is always appreciated.
Stay shiny :D

**Comment by MyShiLingStar** [comment]
Not so fast, speed demon.
This is a big update. It will take some time. 
Please be patient.

**Comment by ThatAnarchyDude** [comment]
I know. lol
I'll be patient.
I just wanted to help make sure you knew they dropped it early. lol

**Comment by jahminique** [comment]
I can't wait I'm so excited

**Comment by jahminique** [comment]
How's everything going 🥰 need hugs
