### ISSUE TITLE
I put in my ip address and it takes me to...

### ISSUE THREAD

**Issue by Forshizuku** [MyShiLingStar/ACNHPoker#11]
Hello i put in my ip address and it takes me to a japanese person stuff which it doesn't even say my name my original animal crossing stuff please help My oringal name is Bri for animal crossing character and ive tried everything i could think of
![hmm](https://user-images.githubusercontent.com/88745523/140401924-b1f22efd-e2a5-4cb2-96e1-5d0803e8bb00.PNG)

**Comment by MyShiLingStar** [comment]
Because you need to wait and update to a new version.
Lucky for you. It is ready.
