### ISSUE TITLE
my computer shows a trojan when downloading this.

### ISSUE THREAD

**Issue by mcorbett26** [MyShiLingStar/ACNHPoker#12]
I am sure its a mistake but my computer is showing it as unsafe to download this file and shows a trojan.

**Comment by MyShiLingStar** [comment]
Homebrew software tends to get flagged as a virus for safety reasons. Here is an online virus result of the .exe file if you need: [virustotal](https://virustotal.com/gui/file/0767945f147d0c449f16f276905912c5f20a36e6e7408a4a6decc395be9e930a/detection)

If you still do not trust it, please send me the trojan result image you are seeing. I can try to send a false positive report to that anti-virus software company.

**Comment by boocrypt** [comment]
Same on me, Windows Defender blocks the download.

![Windows Defender Virus warning - Trojan_Win32_Spursint Q!cl](https://user-images.githubusercontent.com/74729797/140473390-f69b567f-2585-45bb-8920-ab54cd6efcad.jpg)
