### ISSUE TITLE
Windows Defender shows a virus

### ISSUE THREAD

**Issue by boocrypt** [MyShiLingStar/ACNHPoker#14]
Windows Defender blocks the download, because of Trojan:Win32/Spursint.Q!cl. The ACNHPoker Release 17.2 does no issues.

![Windows Defender Virus warning - Trojan_Win32_Spursint Q!cl](https://user-images.githubusercontent.com/74729797/140474492-d8ebc0b9-9fd5-47ac-af41-c2af9110e65c.jpg)

**Comment by violetgaming86** [comment]
turn windows security real time protection off and it should work just fine and keep it off why using acnhporker then when not using porker turn it back on. hope this will help.

**Comment by boocrypt** [comment]
This might help, but is there a Trojan or not 🤔.

**Comment by violetgaming86** [comment]
no there is not a trojan at all.
