### ISSUE TITLE
AcnhPoker crashing when it try to download or extract img.zip

### ISSUE THREAD

**Issue by ELY3M** [MyShiLingStar/ACNHPoker#17]
I believe it have to do with having old files in your folder.     
need to add in a check and delete old files? or force overwrite.      

to reproduce,  go to setting and download image. it will just crash.      

It happened to me for awhile.  I was with my friend and I was updating up her switch and acnhpoker on her pc.    
I updated her acnhpoker to latest one.  I attempted to download new images.   it keep crashing.  
I had to go github release page and manually download and extract.

**Comment by MyShiLingStar** [comment]
ImageDownloader will now delete any existing "img.zip" and download a new one.
A new zip library is used and will now overwrite the old file silently.
