### ISSUE TITLE
Feature Request: item-data JSON dump

### ISSUE THREAD

**Issue by pascalstockert** [MyShiLingStar/ACNHPoker#18]
One of my friends uses this tool to edit their map data - if you already have access to the save data for all the items, would it be possible to dump that data as JSON? 

In that case, one could use the dumped JSON to create a web-app for people to search the location of items through an interactive map!

**Comment by MyShiLingStar** [comment]
If you want the raw JSON files, you can find them [Here](https://github.com/phecdaDia/ACNH)
You can also extract them yourself using the tool on the page.
