### ISSUE TITLE
villagers/turnips

### ISSUE THREAD

**Issue by violetgaming86** [MyShiLingStar/ACNHPoker#20]
max price for turnups are not working and villagers when boxed all say I've moved out and you cant go into there house villagers are there they show up under the map and for max bells when you set it to max the price is not the 999.999.999 bells its a random number and i cant set turnip stack to 30 it a random number.

**Comment by TheSmilez** [comment]
Jesus, punctuation is a thing. I don’t even know how to compile this list because it makes no sense.

**Comment by MyShiLingStar** [comment]
I double-checked those in version 2.0.2. I don't experience any problem.
It sounds like you might have your memory address shifted for some reason.

Did you have some other mod/shit installed?
Please check your atmosphere/contents folder.
430000000000000B (sys-botbase) should be the only folder needed for ACNHPoker.
If you have some other things in there, they could interfere with how sys-botbase works.
Please post an image if you are not sure what they are.

![77D3BA1A-8614-4699-89D9-8148D5E11469](https://user-images.githubusercontent.com/816502/142750687-b837202a-99f5-412f-a03c-50db675ce439.GIF)

**Comment by violetgaming86** [comment]
i had to get  all new internet boxes  ours were out of date so everything has all new ip addresses could that be why and how would i fix that i also dont  run anything extra i keep it simples

**Comment by violetgaming86** [comment]
![Untitled](https://user-images.githubusercontent.com/82244443/142774264-f853c4c5-c2bc-4712-b462-c5c55620d1bb.png)

**Comment by MyShiLingStar** [comment]
Your sys-botbase install does not even look right. 

Why do you still have the "exefs.nsp" in 2017?
And "sys-botbase.nsp" should not be in there.

Please delete the whole 430000000000000B folder.
And download a new one at [here](https://github.com/olliz0r/sys-botbase/releases/download/1.9/sys-botbase.zip).

**Comment by violetgaming86** [comment]
everything is working fine now i deleted the sys-botbase.nsp then put it back in my switch folder  and deleted the other sys-botbase.nsp from contents folder worked just fine and im not sure why sys-botbase.nsp was in there cause its always  in my switch folder and im not sure why it say 2017 all folders are updated thank you for catching that i will fix that.
