### ISSUE TITLE
Keyboard Shortcuts?

### ISSUE THREAD

**Issue by dinosaw** [MyShiLingStar/ACNHPoker#21]
I know they exist, but can we get a list of what they are in all the different modes? I feel like there's many I don't know. And also maybe considering adding an "about" part in the app which links to this github and also shows the shortcut keys.

**Comment by MyShiLingStar** [comment]
https://github.com/MyShiLingStar/ACNHPoker/wiki/Keyboard-&-Mouse-Hotkeys
