### ISSUE TITLE
i  upadte system careless so i have to update my atomsphere but poker doesn't work

### ISSUE THREAD

**Issue by still1987** [MyShiLingStar/ACNHPoker#22]

**Comment by MyShiLingStar** [comment]
Are you sure you have sys-botbase installed properly?
Please check your atmosphere/contents folder.

If the "430000000000000B" folder is missing, Please reinstall your sys-botbase.
You can get a new one [Here](https://github.com/olliz0r/sys-botbase/releases/tag/2.0).

**Comment by still1987** [comment]
![1638686857(1)](https://user-images.githubusercontent.com/94782271/144737186-4df1069e-7f74-40d6-a803-4f488a00e367.png)


i am sure  that sys-botbase installe is it aobut atomphere >
or i should change deepsea
