### ISSUE TITLE
我想知道是否有关于如何使用USB连接的视频教程

### ISSUE THREAD

**Issue by Wanghuanhuany** [MyShiLingStar/ACNHPoker#23]

**Comment by Wanghuanhuany** [comment]
I was wondering if there is a video tutorial on how to use USB connection

**Comment by MyShiLingStar** [comment]
暂时没有, 要花时间录製。

由於usb-botbase只提供了很基本的功能，您有特别原因不能够使用sys-botbase吗？
usb-botbase的速度远远比不上sys-botbase，由於速度太慢了，很多功能都无法正常使用。

**Comment by Wanghuanhuany** [comment]
Because my switch cannot be connected to the Internet, I can only use USB connection
