### ISSUE TITLE
18.8 keeps crashing when I connect to my switch

### ISSUE THREAD

**Issue by Charlotte626** [MyShiLingStar/ACNHPoker#26]
Hey there!

When I connect to my Switch, a message appears saying

'Exception, try restarting the program or reconnecting to the switch'

I click OK and it re-appears another 5 times, then a message saying 

'Value cannot be null. 
Parameter name: value' appears. 

After pressing OK, then the Exception message appears again as it connects to my Switch. I press OK and the whole program closes.

I'm not quite sure what's happened or what I'm doing wrong since I was using 18.8 yesterday with no issues. I've reinstalled it and it's still happening so not quite sure what to do now.

Can anyone help?

Thank you :)

**Comment by MyShiLingStar** [comment]
Hmm...not quite sure about the problem at the moment. Sounds like a connection one.
Poker seems to be able to connect to your switch. But when it tries to poke for the data, it receives nothing or garbage data from it.

1. The first thing to try is to restart your switch first, make sure your home button light up on the home menu.

![FA1D3CDD-F413-4414-B761-C0B66F09A46F](https://user-images.githubusercontent.com/816502/146648827-1933fb1d-0224-4e80-81d6-ab2779294247.GIF)

2. Once you confirm the home button lights up, hold the "L" button and select your game to boot up. Hold it until you see the title screen where it asks you to "Press A". Let it stay at the title screen.

3. Startup Poker and retry the connection.


If your home button does not light up, or the connection still fails, try re-installing the latest sys-botbase. You can get it at : [Here](https://github.com/olliz0r/sys-botbase/releases)


Please post a screenshot if you receive some other new error message.

**Comment by Charlotte626** [comment]
This worked! Thank you so much for your help! You're an absolute star!
