### ISSUE TITLE
No Zodiac Boar Figurine

### ISSUE THREAD

**Issue by acnhmama96** [MyShiLingStar/ACNHPoker#31]
I downloaded the new package today and when I ran the program, it does not list the zodiac boar figurine.

**Comment by moddedx** [comment]
![image](https://user-images.githubusercontent.com/34008111/149048196-4c79409b-5261-45a8-b2ec-ff659269e36a.png)

**Comment by MyShiLingStar** [comment]
Latest Artifacts is : [Here](https://berichan.github.io/GetNHSE/?org=MyShiLingStar&proj=ACNHPoker&projurl=https://github.com/MyShiLingStar/ACNHPoker)

Try download it again.

**Comment by acnhmama96** [comment]
Thank you! That worked. I am unsure what happened, but I now have the correct version!
