### ISSUE TITLE
The single turnip are not working.

### ISSUE THREAD

**Issue by violetgaming86** [MyShiLingStar/ACNHPoker#9]
The single turnip are not working when you are standing over them nothing pops up saying the name of the item or number and you cant pick them up the stacks of turnips are working just fine  its just the single turnips that are not working it stopped working when i was using ACNHPoker 17.1 and im using 17.2 pre Release in hops it would have fixed the problem but it has not.

**Comment by MyShiLingStar** [comment]
The single "turnips" is kind of buggy when placed. I believe it is only for the photo studio.
Try using the "10 turnips" instead. That is the proper item.

**Comment by violetgaming86** [comment]
thank you so much for all your hard work.
